# Generated by Django 5.1.1 on 2024-10-17 01:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phim',
            name='do_tuoi',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('noi_dung', models.TextField()),
                ('phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.phim')),
                ('user_binh_luan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.nguoidung')),
            ],
        ),
    ]
