# Generated by Django 5.1.2 on 2024-11-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_phim_do_tuoi_binhluan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='ten_combo',
            field=models.CharField(max_length=255),
        ),
    ]
